### ISSUE TITLE
Does not build in Ionic AppFlow (Pro Package) with Xcode 10

### ISSUE THREAD

**Issue by JoeMeeks** [opentok/opentok-ionic-samples#42]
When attempting to build this with Ionic AppFlow with Xcode 10 I get the following error:

> [21:40:56]: ▸ Installing "cordova-plugin-opentok" for ios
[21:40:56]: ▸ Failed to install 'cordova-plugin-opentok': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[21:40:56]: ▸ at Context.requireCordovaModule (/usr/local/lib/node_modules/@ionic-enterprise/cordova/node_modules/@ionic-enterprise/cordova-lib/src/hooks/Context.js:57:15)
[21:40:56]: ▸ at module.exports (/Users/ionic/builds/ClearCostHealth/DOCCS/plugins/cordova-plugin-opentok/scripts/downloadiOSSDK.js:7:21)
[21:40:56]: ▸ at runScriptViaModuleLoader (/usr/local/lib/node_modules/@ionic-enterprise/cordova/node_modules/@ionic-enterprise/cordova-lib/src/hooks/HooksRunner.js:181:32)
[21:40:56]: ▸ at runScript (/usr/local/lib/node_modules/@ionic-enterprise/cordova/node_modules/@ionic-enterprise/cordova-lib/src/hooks/HooksRunner.js:157:16)
[21:40:56]: ▸ at /usr/local/lib/node_modules/@ionic-enterprise/cordova/node_modules/@ionic-enterprise/cordova-lib/src/hooks/HooksRunner.js:125:20
[21:40:56]: ▸ at process._tickCallback (internal/process/next_tick.js:68:7)
[21:40:56]: ▸ Failed to restore plugin "cordova-plugin-opentok" from config.xml. You might need to try adding it again. Error: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by JoeMeeks** [comment]
Also when running `ionic cordova plugin add cordova-plugin-opentok` to any existing Ionic project that already has plugins and platforms folders, installation fails with the following errors:

> Installing "cordova-plugin-opentok" for ios
Downloading OpenTok iOS SDK
downloaded
(node:21436) DeprecationWarning: exec: use child_process.execFile instead
expanded
moved OpenTok.framework into C:\ClearCostHealth\DOCCS\plugins\cordova-plugin-opentok/src/ios/
Removed extracted dir
Removed downloaded SDK
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-opentok': CordovaError: Uh oh!
Cannot find framework "C:\ClearCostHealth\DOCCS\plugins\cordova-plugin-opentok\src\ios\OpenTok.framework" for plugin cordova-plugin-opentok in iOS platform
    at install (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\lib\plugman\pluginHandlers.js:109:48)
    at ActionStack.process (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at Api.addPlugin (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\Api.js:234:10)
    at handleInstall (C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
(node:21436) UnhandledPromiseRejectionWarning: CordovaError: Uh oh!
Cannot find framework "C:\ClearCostHealth\DOCCS\plugins\cordova-plugin-opentok\src\ios\OpenTok.framework" for plugin cordova-plugin-opentok in iOS platform
    at install (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\lib\plugman\pluginHandlers.js:109:48)
    at ActionStack.process (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at Api.addPlugin (C:\ClearCostHealth\DOCCS\platforms\ios\cordova\Api.js:234:10)
    at handleInstall (C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
(node:21436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at Promise.promise.promiseDispatch (C:\Users\jmeeks\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)

The initial attempt using a this cloned opentok-ionic-samples repo worked because it did not already have platforms & plugins folders.
