### ISSUE TITLE
Installation fails for iOS: CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported

### ISSUE THREAD

**Issue by lqrz** [opentok/opentok-ionic-samples#65]
When I run `ionic cordova plugin add cordova-plugin-opentok` I get the following error for iOS:
```
CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported.
```

Here the full log:
```
Installing "cordova-plugin-opentok" for ios

Failed to install 'cordova-plugin-opentok': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/lqrz/Documents/lqrz/doctors/mobileapp/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/lqrz/Documents/lqrz/doctors/mobileapp/plugins/cordova-plugin-opentok/scripts/downloadiOSSDK.js:7:21)
    at runScriptViaModuleLoader (/Users/lqrz/Documents/lqrz/doctors/mobileapp/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/lqrz/Documents/lqrz/doctors/mobileapp/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/lqrz/Documents/lqrz/doctors/mobileapp/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)

Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
[ERROR] An error occurred while running cordova plugin add cordova-plugin-opentok --save (exit code 1).
```

**Comment by lqrz** [comment]
See: https://github.com/opentok/cordova-plugin-opentok/issues/180

**Comment by yelji** [comment]
I have the similar issue! did you resolve it?
